name: Activate Unity
on: [push]
jobs:
  requestActivation:
    name: Request activation âœ”
    runs-on: ubuntu-latest
    steps:
      - name: Activate Unity
        uses: webbertakken/unity-activate@v1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_ALF }}
        with:
          unityVersion: 2018.4.13f1
