name: Acquire activation file # è©²Actionçš„åç¨±ï¼Œå°‡é¡¯ç¤ºåœ¨Github Actionçš„é é¢UI
on: repository_dispatch  #è§¸ç™¼Actionçš„æ¢ä»¶ï¼Œæ”¹ç‚ºrepository_dispatchè§¸ç™¼
jobs: # å·¥ä½œé …ç›®ï¼Œå¯å¹³è¡Œè™•ç†ã€‚
  activation: # å·¥ä½œé …ç›®çš„è®Šæ•¸å
    name: Request manual activation file ğŸ”‘ # å·¥ä½œé …ç›®çš„é¡¯ç¤ºåç¨±ï¼Œå°‡é¡¯ç¤ºåœ¨Actioné é¢UIä¸Šã€‚
    if: github.event.action == 'request_activation_file' # åˆ¤æ–·å‚³å…¥åƒæ•¸æ˜¯å¦ç‚ºrequest_activation_fileï¼Œæ˜¯æ‰æœƒé‹è¡Œã€‚æ³¨æ„github.event.actionå³curlå‚³å…¥çš„åƒæ•¸event_type
    runs-on: ubuntu-latest # é‹è¡Œçš„è£ç½®
    steps:
        # Request manual activation file
        - name: Request manual activation file # é¡¯ç¤ºåç¨±
          id: getManualLicenseFile # è®Šæ•¸åï¼Œå…§éƒ¨ä½¿ç”¨
          uses: webbertakken/unity-request-manual-activation-file@v1.1 # å¼•ç”¨å¤–éƒ¨æ–¹æ³•ã€‚
          with: # withç”¨æ–¼è¼¸å…¥åƒæ•¸ï¼Œå¯æƒ³åƒæˆä¸Šé¢æ˜¯ä¸€å€‹å«getManualLicenseFile()çš„å‡½æ•¸/æ–¹æ³•
            unityVersion: 2018.4.13f1 # åƒæ•¸ï¼Œç”¨æ–¼è¼¸å…¥é€²ä¸Šæ–¹çš„å‡½æ•¸/æ–¹æ³•ã€‚
        # Upload artifact (Unity_v20XX.X.XXXX.alf)
        - name: Expose as artifact
          uses: actions/upload-artifact@v1 # å¼•ç”¨å¤–éƒ¨æ–¹æ³•ï¼Œè©²æ–¹æ³•ç‚ºå°‡æŒ‡å®šè·¯å¾‘ä¸‹çš„æª”æ¡ˆä¸Šå‚³ç‚ºartifactã€‚
          with:
            name: ${{ steps.getManualLicenseFile.outputs.filePath }} # å¼•ç”¨ä¸Šé¢step1çš„è¼¸å‡ºå€¼(outputs)
            path: ${{ steps.getManualLicenseFile.outputs.filePath }} # å¼•ç”¨ä¸Šé¢step1çš„è¼¸å‡ºå€¼(outputs)